-- vim.o.statuscolumn = "%!v:lnum"
-- vim.o.statuscolumn = "%!v:virtnum"
-- vim.o.statuscolumn = "%!v:lua.require('statcol'). myStatuscolumn()"
-- vim.o.virt
-- vim.o.sta
-- vim.v.maxcol
-- vim.o.statu
-- vim.o.signcolumn = "yes"
-- scolumn = "%!v:lua.require('s'). myStatuscolumn()"
-- vim.o.statusline
